---
# Source: exporter-node/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "prometheus"
    chart: exporter-node-0.4.0
    prometheus: kube-prometheus
    release: "exporter-node"
    role: alert-rules
  name: kube-prometheus-exporter-node
data:
  node.rules: |-
    groups:
    - name: node.rules
      rules:
      - record: instance:node_cpu:rate:sum
        expr: sum(rate(node_cpu{mode!="idle",mode!="iowait"}[3m]))
          BY (instance)
      - record: instance:node_filesystem_usage:sum
        expr: sum((node_filesystem_size{mountpoint="/"} - node_filesystem_free{mountpoint="/"}))
          BY (instance)
      - record: instance:node_network_receive_bytes:rate:sum
        expr: sum(rate(node_network_receive_bytes[3m])) BY (instance)
      - record: instance:node_network_transmit_bytes:rate:sum
        expr: sum(rate(node_network_transmit_bytes[3m])) BY (instance)
      - record: instance:node_cpu:ratio
        expr: sum(rate(node_cpu{mode!="idle",mode!="iowait"}[5m])) WITHOUT (cpu, mode) / ON(instance)
          GROUP_LEFT() count(sum(node_cpu) BY (instance, cpu)) BY (instance)
      - record: cluster:node_cpu:sum_rate5m
        expr: sum(rate(node_cpu{mode!="idle",mode!="iowait"}[5m]))
      - record: cluster:node_cpu:ratio
        expr: cluster:node_cpu:rate5m / count(sum(node_cpu) BY (instance, cpu))
      - alert: NodeExporterDown
        expr: absent(up{job="node-exporter"} == 1)
        for: 10m
        labels:
          severity: warning
        annotations:
          description: Prometheus could not scrape a node-exporter for more than 10m,
            or node-exporters have disappeared from discovery
          summary: Prometheus could not scrape a node-exporter
      - alert: NodeDiskRunningFull
        expr: predict_linear(node_filesystem_free[6h], 3600 * 24) < 0
        for: 30m
        labels:
          severity: warning
        annotations:
          description: device {{$labels.device}} on node {{$labels.instance}} is running
            full within the next 24 hours (mounted at {{$labels.mountpoint}})
          summary: Node disk is running full within 24 hours
      - alert: NodeDiskRunningFull
        expr: predict_linear(node_filesystem_free[30m], 3600 * 2) < 0
        for: 10m
        labels:
          severity: critical
        annotations:
          description: device {{$labels.device}} on node {{$labels.instance}} is running
            full within the next 2 hours (mounted at {{$labels.mountpoint}})
          summary: Node disk is running full within 2 hours



---
# Source: exporter-node/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube-prometheus-exporter-node
  labels:
    app: exporter-node
    component: node-exporter
    release: "exporter-node"
    chart: exporter-node-0.4.0
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics

---
# Source: exporter-node/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: exporter-node
    chart: "exporter-node-0.4.0"
    component: node-exporter
    release: "exporter-node"
    prometheus: kube-prometheus
  name: kube-prometheus-exporter-node
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: exporter-node
      component: node-exporter
  namespaceSelector:
    matchNames:
      - "kube-ops"
  endpoints:
  - port: metrics
    interval: 15s

---
# Source: exporter-node/templates/daemonset.yaml


---
# Source: exporter-node/templates/endpoints.yaml


---
# Source: exporter-node/templates/node.rules.yaml

---
# Source: exporter-node/templates/psp-clusterrole.yaml


---
# Source: exporter-node/templates/psp-clusterrolebinding.yaml


---
# Source: exporter-node/templates/psp.yaml


---
# Source: exporter-node/templates/serviceaccount.yaml


